<Info>
  <Time>20.06.2017 13:37:18</Time>
  <Info>Entered Pass = 123user!</Info>
</Info>
<Info>
  <Time>20.06.2017 13:37:18</Time>
  <Info>HashPass = A4675BD2258B1137E92B13BFF1D4BD2C096E6152CF20C77704EBD648ABDB887808D72500BDFFF3D87AEE6A8A894C79DBC56EE758F58DD7CD2995A5704D22EAAD</Info>
</Info>
<Xcpt>
  <Time>20.06.2017 13:38:32</Time>
  <Exception>
    <Source>EntityFramework</Source>
    <Message>Der Vorgang ist fehlgeschlagen: Die Beziehung konnte nicht geändert werden, da für mindestens eine der Fremdschlüsseleigenschaften keine NULL-Werte zulässig sind. Wenn eine Beziehung geändert wird, wird die verwandte Fremdschlüsseleigenschaft auf einen NULL-Wert festgelegt. Wenn der Fremdschlüssel keine NULL-Werte unterstützt, muss eine neue Beziehung definiert, die Fremdschlüsseleigenschaft einem anderen Nicht-NULL-Wert zugeordnet oder das nicht verwandte Objekt gelöscht werden.</Message>
    <Stack>   bei System.Data.Entity.Core.Objects.ObjectContext.PrepareToSaveChanges(SaveOptions options)
   bei System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
   bei System.Data.Entity.Internal.InternalContext.SaveChanges()
   bei CardGame.DAL.Logic.DeckManager.UpdateDeckById(Int32 id, List`1 deckCards) in C:\Users\cervchri\Documents\GitHub\LAP-CardShop\CardGameLap\CardGame\CardGame.DAL\Logic\DeckManager.cs:Zeile 137.</Stack>
  </Exception>
</Xcpt>
<Info>
  <Time>20.06.2017 13:43:06</Time>
  <Info>id: 4</Info>
</Info>
<Info>
  <Time>20.06.2017 14:08:28</Time>
  <Info>id: 4</Info>
</Info>
<Info>
  <Time>20.06.2017 14:14:29</Time>
  <Info>id: 4</Info>
</Info>
<Info>
  <Time>20.06.2017 14:43:16</Time>
  <Info>id: 4</Info>
</Info>
<Info>
  <Time>20.06.2017 14:56:28</Time>
  <Info>id: 5</Info>
</Info>
<Xcpt>
  <Time>20.06.2017 14:58:58</Time>
  <Exception>
    <Source>CardGame.DAL</Source>
    <Message>UserDoesNotExist</Message>
    <Stack>   bei CardGame.DAL.Logic.AuthManager.AuthUser(String email, String password) in C:\Users\cervchri\Documents\GitHub\LAP-CardShop\CardGameLap\CardGame\CardGame.DAL\Logic\AuthManager.cs:Zeile 60.</Stack>
  </Exception>
</Xcpt>
<Xcpt>
  <Time>20.06.2017 14:58:58</Time>
  <Exception>
    <Source>CardGame.DAL</Source>
    <Message>User Does Not Exist</Message>
    <Stack>   bei CardGame.DAL.Logic.UserManager.GetRoleNamesByEmail(String email) in C:\Users\cervchri\Documents\GitHub\LAP-CardShop\CardGameLap\CardGame\CardGame.DAL\Logic\UserManager.cs:Zeile 123.</Stack>
  </Exception>
</Xcpt>
<Xcpt>
  <Time>20.06.2017 14:58:58</Time>
  <Exception>
    <Source>CardGame.DAL</Source>
    <Message>User Does Not Exist</Message>
    <Stack>   bei CardGame.DAL.Logic.UserManager.GetPersonByEmail(String email) in C:\Users\cervchri\Documents\GitHub\LAP-CardShop\CardGameLap\CardGame\CardGame.DAL\Logic\UserManager.cs:Zeile 89.</Stack>
  </Exception>
</Xcpt>
<Xcpt>
  <Time>20.06.2017 15:00:18</Time>
  <Exception>
    <Source>EntityFramework</Source>
    <Message>Fehler bei der Überprüfung einer oder mehrerer Entitäten. Weitere Informationen finden Sie in den Erläuterungen zur EntityValidationErrors-Eigenschaft.</Message>
    <Stack>   bei System.Data.Entity.Internal.InternalContext.SaveChanges()
   bei CardGame.DAL.Logic.AuthManager.Register(Person regUser) in C:\Users\cervchri\Documents\GitHub\LAP-CardShop\CardGameLap\CardGame\CardGame.DAL\Logic\AuthManager.cs:Zeile 33.</Stack>
  </Exception>
</Xcpt>
<Xcpt>
  <Time>20.06.2017 15:00:19</Time>
  <Exception>
    <Source>CardGame.DAL</Source>
    <Message>User Does Not Exist</Message>
    <Stack>   bei CardGame.DAL.Logic.UserManager.GetPersonByEmail(String email) in C:\Users\cervchri\Documents\GitHub\LAP-CardShop\CardGameLap\CardGame\CardGame.DAL\Logic\UserManager.cs:Zeile 89.</Stack>
  </Exception>
</Xcpt>
<Xcpt>
  <Time>20.06.2017 15:00:46</Time>
  <Exception>
    <Source>CardGame.DAL</Source>
    <Message>UserDoesNotExist</Message>
    <Stack>   bei CardGame.DAL.Logic.AuthManager.AuthUser(String email, String password) in C:\Users\cervchri\Documents\GitHub\LAP-CardShop\CardGameLap\CardGame\CardGame.DAL\Logic\AuthManager.cs:Zeile 60.</Stack>
  </Exception>
</Xcpt>
<Xcpt>
  <Time>20.06.2017 15:00:46</Time>
  <Exception>
    <Source>CardGame.DAL</Source>
    <Message>User Does Not Exist</Message>
    <Stack>   bei CardGame.DAL.Logic.UserManager.GetRoleNamesByEmail(String email) in C:\Users\cervchri\Documents\GitHub\LAP-CardShop\CardGameLap\CardGame\CardGame.DAL\Logic\UserManager.cs:Zeile 123.</Stack>
  </Exception>
</Xcpt>
<Xcpt>
  <Time>20.06.2017 15:00:46</Time>
  <Exception>
    <Source>CardGame.DAL</Source>
    <Message>User Does Not Exist</Message>
    <Stack>   bei CardGame.DAL.Logic.UserManager.GetPersonByEmail(String email) in C:\Users\cervchri\Documents\GitHub\LAP-CardShop\CardGameLap\CardGame\CardGame.DAL\Logic\UserManager.cs:Zeile 89.</Stack>
  </Exception>
</Xcpt>
<Xcpt>
  <Time>20.06.2017 15:02:14</Time>
  <Exception>
    <Source>CardGame.DAL</Source>
    <Message>UserDoesNotExist</Message>
    <Stack>   bei CardGame.DAL.Logic.AuthManager.AuthUser(String email, String password) in C:\Users\cervchri\Documents\GitHub\LAP-CardShop\CardGameLap\CardGame\CardGame.DAL\Logic\AuthManager.cs:Zeile 60.</Stack>
  </Exception>
</Xcpt>
<Xcpt>
  <Time>20.06.2017 15:02:14</Time>
  <Exception>
    <Source>CardGame.DAL</Source>
    <Message>User Does Not Exist</Message>
    <Stack>   bei CardGame.DAL.Logic.UserManager.GetRoleNamesByEmail(String email) in C:\Users\cervchri\Documents\GitHub\LAP-CardShop\CardGameLap\CardGame\CardGame.DAL\Logic\UserManager.cs:Zeile 123.</Stack>
  </Exception>
</Xcpt>
<Xcpt>
  <Time>20.06.2017 15:02:14</Time>
  <Exception>
    <Source>CardGame.DAL</Source>
    <Message>User Does Not Exist</Message>
    <Stack>   bei CardGame.DAL.Logic.UserManager.GetPersonByEmail(String email) in C:\Users\cervchri\Documents\GitHub\LAP-CardShop\CardGameLap\CardGame\CardGame.DAL\Logic\UserManager.cs:Zeile 89.</Stack>
  </Exception>
</Xcpt>
<Info>
  <Time>20.06.2017 15:02:32</Time>
  <Info>Entered Pass = </Info>
</Info>
<Info>
  <Time>20.06.2017 15:02:32</Time>
  <Info>HashPass = E3B73CC967423A75C31BA80024C45A38190404FA26A9AC3B6358CE634372C22939BDFA27D5B68AD3D6E76770A0CD31A94A1CD4574945EC1450788E785026E0AA</Info>
</Info>
<Xcpt>
  <Time>20.06.2017 15:02:32</Time>
  <Exception>
    <Source>CardGame.DAL</Source>
    <Message>User Does Not Exist</Message>
    <Stack>   bei CardGame.DAL.Logic.UserManager.GetPersonByEmail(String email) in C:\Users\cervchri\Documents\GitHub\LAP-CardShop\CardGameLap\CardGame\CardGame.DAL\Logic\UserManager.cs:Zeile 89.</Stack>
  </Exception>
</Xcpt>
<Xcpt>
  <Time>20.06.2017 15:03:31</Time>
  <Exception>
    <Source>CardGame.DAL</Source>
    <Message>UserDoesNotExist</Message>
    <Stack>   bei CardGame.DAL.Logic.AuthManager.AuthUser(String email, String password) in C:\Users\cervchri\Documents\GitHub\LAP-CardShop\CardGameLap\CardGame\CardGame.DAL\Logic\AuthManager.cs:Zeile 60.</Stack>
  </Exception>
</Xcpt>
<Xcpt>
  <Time>20.06.2017 15:03:31</Time>
  <Exception>
    <Source>CardGame.DAL</Source>
    <Message>User Does Not Exist</Message>
    <Stack>   bei CardGame.DAL.Logic.UserManager.GetRoleNamesByEmail(String email) in C:\Users\cervchri\Documents\GitHub\LAP-CardShop\CardGameLap\CardGame\CardGame.DAL\Logic\UserManager.cs:Zeile 123.</Stack>
  </Exception>
</Xcpt>
<Xcpt>
  <Time>20.06.2017 15:03:31</Time>
  <Exception>
    <Source>CardGame.DAL</Source>
    <Message>User Does Not Exist</Message>
    <Stack>   bei CardGame.DAL.Logic.UserManager.GetPersonByEmail(String email) in C:\Users\cervchri\Documents\GitHub\LAP-CardShop\CardGameLap\CardGame\CardGame.DAL\Logic\UserManager.cs:Zeile 89.</Stack>
  </Exception>
</Xcpt>
<Xcpt>
  <Time>20.06.2017 15:06:19</Time>
  <Exception>
    <Source>CardGame.DAL</Source>
    <Message>UserDoesNotExist</Message>
    <Stack>   bei CardGame.DAL.Logic.AuthManager.AuthUser(String email, String password) in C:\Users\cervchri\Documents\GitHub\LAP-CardShop\CardGameLap\CardGame\CardGame.DAL\Logic\AuthManager.cs:Zeile 60.</Stack>
  </Exception>
</Xcpt>
<Xcpt>
  <Time>20.06.2017 15:06:19</Time>
  <Exception>
    <Source>CardGame.DAL</Source>
    <Message>User Does Not Exist</Message>
    <Stack>   bei CardGame.DAL.Logic.UserManager.GetRoleNamesByEmail(String email) in C:\Users\cervchri\Documents\GitHub\LAP-CardShop\CardGameLap\CardGame\CardGame.DAL\Logic\UserManager.cs:Zeile 123.</Stack>
  </Exception>
</Xcpt>
<Xcpt>
  <Time>20.06.2017 15:06:19</Time>
  <Exception>
    <Source>CardGame.DAL</Source>
    <Message>User Does Not Exist</Message>
    <Stack>   bei CardGame.DAL.Logic.UserManager.GetPersonByEmail(String email) in C:\Users\cervchri\Documents\GitHub\LAP-CardShop\CardGameLap\CardGame\CardGame.DAL\Logic\UserManager.cs:Zeile 89.</Stack>
  </Exception>
</Xcpt>
<Xcpt>
  <Time>20.06.2017 15:09:17</Time>
  <Exception>
    <Source>CardGame.DAL</Source>
    <Message>UserDoesNotExist</Message>
    <Stack>   bei CardGame.DAL.Logic.AuthManager.AuthUser(String email, String password) in C:\Users\cervchri\Documents\GitHub\LAP-CardShop\CardGameLap\CardGame\CardGame.DAL\Logic\AuthManager.cs:Zeile 60.</Stack>
  </Exception>
</Xcpt>
<Xcpt>
  <Time>20.06.2017 15:09:17</Time>
  <Exception>
    <Source>CardGame.DAL</Source>
    <Message>User Does Not Exist</Message>
    <Stack>   bei CardGame.DAL.Logic.UserManager.GetRoleNamesByEmail(String email) in C:\Users\cervchri\Documents\GitHub\LAP-CardShop\CardGameLap\CardGame\CardGame.DAL\Logic\UserManager.cs:Zeile 123.</Stack>
  </Exception>
</Xcpt>
<Xcpt>
  <Time>20.06.2017 15:09:17</Time>
  <Exception>
    <Source>CardGame.DAL</Source>
    <Message>User Does Not Exist</Message>
    <Stack>   bei CardGame.DAL.Logic.UserManager.GetPersonByEmail(String email) in C:\Users\cervchri\Documents\GitHub\LAP-CardShop\CardGameLap\CardGame\CardGame.DAL\Logic\UserManager.cs:Zeile 89.</Stack>
  </Exception>
</Xcpt>
<Info>
  <Time>20.06.2017 15:12:28</Time>
  <Info>Entered Pass = 123user!</Info>
</Info>
<Info>
  <Time>20.06.2017 15:12:28</Time>
  <Info>HashPass = A4675BD2258B1137E92B13BFF1D4BD2C096E6152CF20C77704EBD648ABDB887808D72500BDFFF3D87AEE6A8A894C79DBC56EE758F58DD7CD2995A5704D22EAAD</Info>
</Info>
<Info>
  <Time>20.06.2017 15:12:33</Time>
  <Info>id: 5</Info>
</Info>
<Info>
  <Time>20.06.2017 15:19:14</Time>
  <Info>Entered Pass = 123user!</Info>
</Info>
<Info>
  <Time>20.06.2017 15:19:14</Time>
  <Info>HashPass = A4675BD2258B1137E92B13BFF1D4BD2C096E6152CF20C77704EBD648ABDB887808D72500BDFFF3D87AEE6A8A894C79DBC56EE758F58DD7CD2995A5704D22EAAD</Info>
</Info>
<Info>
  <Time>20.06.2017 15:23:03</Time>
  <Info>Entered Pass = jungsue1</Info>
</Info>
<Info>
  <Time>20.06.2017 15:23:03</Time>
  <Info>HashPass = 9438D371A7460D47D5805D72D43803F7271AA0CDEDA1ED8A29777EE19C1E43189B9985EA2FB4932CFDFB271C654E2A0DF61B67482B85EBE182027A58C462CFD2</Info>
</Info>
<Info>
  <Time>20.06.2017 15:39:06</Time>
  <Info>Entered Pass = 123user!</Info>
</Info>
<Info>
  <Time>20.06.2017 15:39:06</Time>
  <Info>HashPass = A4675BD2258B1137E92B13BFF1D4BD2C096E6152CF20C77704EBD648ABDB887808D72500BDFFF3D87AEE6A8A894C79DBC56EE758F58DD7CD2995A5704D22EAAD</Info>
</Info>
<Info>
  <Time>20.06.2017 15:40:25</Time>
  <Info>id: 1</Info>
</Info>
<Info>
  <Time>20.06.2017 15:40:43</Time>
  <Info>id: 2</Info>
</Info>
<Xcpt>
  <Time>20.06.2017 15:41:47</Time>
  <Exception>
    <Source>EntityFramework</Source>
    <Message>Der Vorgang ist fehlgeschlagen: Die Beziehung konnte nicht geändert werden, da für mindestens eine der Fremdschlüsseleigenschaften keine NULL-Werte zulässig sind. Wenn eine Beziehung geändert wird, wird die verwandte Fremdschlüsseleigenschaft auf einen NULL-Wert festgelegt. Wenn der Fremdschlüssel keine NULL-Werte unterstützt, muss eine neue Beziehung definiert, die Fremdschlüsseleigenschaft einem anderen Nicht-NULL-Wert zugeordnet oder das nicht verwandte Objekt gelöscht werden.</Message>
    <Stack>   bei System.Data.Entity.Core.Objects.ObjectContext.PrepareToSaveChanges(SaveOptions options)
   bei System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
   bei System.Data.Entity.Internal.InternalContext.SaveChanges()
   bei CardGame.DAL.Logic.DeckManager.UpdateDeckById(Int32 id, List`1 deckCards) in C:\Users\cervchri\Documents\GitHub\LAP-CardShop\CardGameLap\CardGame\CardGame.DAL\Logic\DeckManager.cs:Zeile 137.</Stack>
  </Exception>
</Xcpt>
<Xcpt>
  <Time>20.06.2017 15:42:04</Time>
  <Exception>
    <Source>EntityFramework</Source>
    <Message>Der Vorgang ist fehlgeschlagen: Die Beziehung konnte nicht geändert werden, da für mindestens eine der Fremdschlüsseleigenschaften keine NULL-Werte zulässig sind. Wenn eine Beziehung geändert wird, wird die verwandte Fremdschlüsseleigenschaft auf einen NULL-Wert festgelegt. Wenn der Fremdschlüssel keine NULL-Werte unterstützt, muss eine neue Beziehung definiert, die Fremdschlüsseleigenschaft einem anderen Nicht-NULL-Wert zugeordnet oder das nicht verwandte Objekt gelöscht werden.</Message>
    <Stack>   bei System.Data.Entity.Core.Objects.ObjectContext.PrepareToSaveChanges(SaveOptions options)
   bei System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
   bei System.Data.Entity.Internal.InternalContext.SaveChanges()
   bei CardGame.DAL.Logic.DeckManager.UpdateDeckById(Int32 id, List`1 deckCards) in C:\Users\cervchri\Documents\GitHub\LAP-CardShop\CardGameLap\CardGame\CardGame.DAL\Logic\DeckManager.cs:Zeile 137.</Stack>
  </Exception>
</Xcpt>
<Xcpt>
  <Time>20.06.2017 15:42:26</Time>
  <Exception>
    <Source>EntityFramework</Source>
    <Message>Der Vorgang ist fehlgeschlagen: Die Beziehung konnte nicht geändert werden, da für mindestens eine der Fremdschlüsseleigenschaften keine NULL-Werte zulässig sind. Wenn eine Beziehung geändert wird, wird die verwandte Fremdschlüsseleigenschaft auf einen NULL-Wert festgelegt. Wenn der Fremdschlüssel keine NULL-Werte unterstützt, muss eine neue Beziehung definiert, die Fremdschlüsseleigenschaft einem anderen Nicht-NULL-Wert zugeordnet oder das nicht verwandte Objekt gelöscht werden.</Message>
    <Stack>   bei System.Data.Entity.Core.Objects.ObjectContext.PrepareToSaveChanges(SaveOptions options)
   bei System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
   bei System.Data.Entity.Internal.InternalContext.SaveChanges()
   bei CardGame.DAL.Logic.DeckManager.UpdateDeckById(Int32 id, List`1 deckCards) in C:\Users\cervchri\Documents\GitHub\LAP-CardShop\CardGameLap\CardGame\CardGame.DAL\Logic\DeckManager.cs:Zeile 137.</Stack>
  </Exception>
</Xcpt>
<Xcpt>
  <Time>20.06.2017 15:42:41</Time>
  <Exception>
    <Source>EntityFramework</Source>
    <Message>Der Vorgang ist fehlgeschlagen: Die Beziehung konnte nicht geändert werden, da für mindestens eine der Fremdschlüsseleigenschaften keine NULL-Werte zulässig sind. Wenn eine Beziehung geändert wird, wird die verwandte Fremdschlüsseleigenschaft auf einen NULL-Wert festgelegt. Wenn der Fremdschlüssel keine NULL-Werte unterstützt, muss eine neue Beziehung definiert, die Fremdschlüsseleigenschaft einem anderen Nicht-NULL-Wert zugeordnet oder das nicht verwandte Objekt gelöscht werden.</Message>
    <Stack>   bei System.Data.Entity.Core.Objects.ObjectContext.PrepareToSaveChanges(SaveOptions options)
   bei System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
   bei System.Data.Entity.Internal.InternalContext.SaveChanges()
   bei CardGame.DAL.Logic.DeckManager.UpdateDeckById(Int32 id, List`1 deckCards) in C:\Users\cervchri\Documents\GitHub\LAP-CardShop\CardGameLap\CardGame\CardGame.DAL\Logic\DeckManager.cs:Zeile 137.</Stack>
  </Exception>
</Xcpt>
<Xcpt>
  <Time>20.06.2017 15:44:47</Time>
  <Exception>
    <Source>EntityFramework</Source>
    <Message>Der Vorgang ist fehlgeschlagen: Die Beziehung konnte nicht geändert werden, da für mindestens eine der Fremdschlüsseleigenschaften keine NULL-Werte zulässig sind. Wenn eine Beziehung geändert wird, wird die verwandte Fremdschlüsseleigenschaft auf einen NULL-Wert festgelegt. Wenn der Fremdschlüssel keine NULL-Werte unterstützt, muss eine neue Beziehung definiert, die Fremdschlüsseleigenschaft einem anderen Nicht-NULL-Wert zugeordnet oder das nicht verwandte Objekt gelöscht werden.</Message>
    <Stack>   bei System.Data.Entity.Core.Objects.ObjectContext.PrepareToSaveChanges(SaveOptions options)
   bei System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
   bei System.Data.Entity.Internal.InternalContext.SaveChanges()
   bei CardGame.DAL.Logic.DeckManager.UpdateDeckById(Int32 id, List`1 deckCards) in C:\Users\cervchri\Documents\GitHub\LAP-CardShop\CardGameLap\CardGame\CardGame.DAL\Logic\DeckManager.cs:Zeile 137.</Stack>
  </Exception>
</Xcpt>
<Xcpt>
  <Time>20.06.2017 15:45:18</Time>
  <Exception>
    <Source>EntityFramework</Source>
    <Message>Der Vorgang ist fehlgeschlagen: Die Beziehung konnte nicht geändert werden, da für mindestens eine der Fremdschlüsseleigenschaften keine NULL-Werte zulässig sind. Wenn eine Beziehung geändert wird, wird die verwandte Fremdschlüsseleigenschaft auf einen NULL-Wert festgelegt. Wenn der Fremdschlüssel keine NULL-Werte unterstützt, muss eine neue Beziehung definiert, die Fremdschlüsseleigenschaft einem anderen Nicht-NULL-Wert zugeordnet oder das nicht verwandte Objekt gelöscht werden.</Message>
    <Stack>   bei System.Data.Entity.Core.Objects.ObjectContext.PrepareToSaveChanges(SaveOptions options)
   bei System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
   bei System.Data.Entity.Internal.InternalContext.SaveChanges()
   bei CardGame.DAL.Logic.DeckManager.UpdateDeckById(Int32 id, List`1 deckCards) in C:\Users\cervchri\Documents\GitHub\LAP-CardShop\CardGameLap\CardGame\CardGame.DAL\Logic\DeckManager.cs:Zeile 137.</Stack>
  </Exception>
</Xcpt>
<Info>
  <Time>20.06.2017 15:45:29</Time>
  <Info>id: 4</Info>
</Info>
<Info>
  <Time>20.06.2017 15:46:07</Time>
  <Info>id: 1</Info>
</Info>
<Info>
  <Time>20.06.2017 15:46:21</Time>
  <Info>id: 3</Info>
</Info>
<Info>
  <Time>20.06.2017 15:46:32</Time>
  <Info>id: 4</Info>
</Info>
<Info>
  <Time>20.06.2017 15:47:26</Time>
  <Info>Entered Pass = 123user!</Info>
</Info>
<Info>
  <Time>20.06.2017 15:47:26</Time>
  <Info>HashPass = A4675BD2258B1137E92B13BFF1D4BD2C096E6152CF20C77704EBD648ABDB887808D72500BDFFF3D87AEE6A8A894C79DBC56EE758F58DD7CD2995A5704D22EAAD</Info>
</Info>
<Info>
  <Time>20.06.2017 15:48:26</Time>
  <Info>Entered Pass = 123user!</Info>
</Info>
<Info>
  <Time>20.06.2017 15:48:26</Time>
  <Info>HashPass = A4675BD2258B1137E92B13BFF1D4BD2C096E6152CF20C77704EBD648ABDB887808D72500BDFFF3D87AEE6A8A894C79DBC56EE758F58DD7CD2995A5704D22EAAD</Info>
</Info>
<Xcpt>
  <Time>20.06.2017 15:48:26</Time>
  <Exception>
    <Source>CardGame.DAL</Source>
    <Message>User Does Not Exist</Message>
    <Stack>   bei CardGame.DAL.Logic.UserManager.GetPersonByEmail(String email) in C:\Users\cervchri\Documents\GitHub\LAP-CardShop\CardGameLap\CardGame\CardGame.DAL\Logic\UserManager.cs:Zeile 89.</Stack>
  </Exception>
</Xcpt>
<Info>
  <Time>20.06.2017 15:48:39</Time>
  <Info>Entered Pass = 123user!</Info>
</Info>
<Info>
  <Time>20.06.2017 15:48:39</Time>
  <Info>HashPass = A4675BD2258B1137E92B13BFF1D4BD2C096E6152CF20C77704EBD648ABDB887808D72500BDFFF3D87AEE6A8A894C79DBC56EE758F58DD7CD2995A5704D22EAAD</Info>
</Info>
<Xcpt>
  <Time>20.06.2017 15:48:40</Time>
  <Exception>
    <Source>CardGame.DAL</Source>
    <Message>User Does Not Exist</Message>
    <Stack>   bei CardGame.DAL.Logic.UserManager.GetPersonByEmail(String email) in C:\Users\cervchri\Documents\GitHub\LAP-CardShop\CardGameLap\CardGame\CardGame.DAL\Logic\UserManager.cs:Zeile 89.</Stack>
  </Exception>
</Xcpt>
<Info>
  <Time>20.06.2017 15:48:59</Time>
  <Info>Entered Pass = 123user!</Info>
</Info>
<Info>
  <Time>20.06.2017 15:48:59</Time>
  <Info>HashPass = A4675BD2258B1137E92B13BFF1D4BD2C096E6152CF20C77704EBD648ABDB887808D72500BDFFF3D87AEE6A8A894C79DBC56EE758F58DD7CD2995A5704D22EAAD</Info>
</Info>
<Xcpt>
  <Time>20.06.2017 15:48:59</Time>
  <Exception>
    <Source>CardGame.DAL</Source>
    <Message>User Does Not Exist</Message>
    <Stack>   bei CardGame.DAL.Logic.UserManager.GetPersonByEmail(String email) in C:\Users\cervchri\Documents\GitHub\LAP-CardShop\CardGameLap\CardGame\CardGame.DAL\Logic\UserManager.cs:Zeile 89.</Stack>
  </Exception>
</Xcpt>
<Info>
  <Time>20.06.2017 15:57:53</Time>
  <Info>Entered Pass = 123user!</Info>
</Info>
<Info>
  <Time>20.06.2017 15:57:53</Time>
  <Info>HashPass = 956CC5E18891998E782E67C924F6227DF121CDBAF7599071B75C8F4466CC8E350A90016E566EF04E793FD2F79423795CA614F12C828D26F99F507D652CE9E0FD</Info>
</Info>
<Info>
  <Time>20.06.2017 15:58:33</Time>
  <Info>id: 2</Info>
</Info>
<Info>
  <Time>20.06.2017 15:58:43</Time>
  <Info>id: 2</Info>
</Info>
<Xcpt>
  <Time>20.06.2017 16:13:26</Time>
  <Exception>
    <Source>EntityFramework</Source>
    <Message>Der Vorgang ist fehlgeschlagen: Die Beziehung konnte nicht geändert werden, da für mindestens eine der Fremdschlüsseleigenschaften keine NULL-Werte zulässig sind. Wenn eine Beziehung geändert wird, wird die verwandte Fremdschlüsseleigenschaft auf einen NULL-Wert festgelegt. Wenn der Fremdschlüssel keine NULL-Werte unterstützt, muss eine neue Beziehung definiert, die Fremdschlüsseleigenschaft einem anderen Nicht-NULL-Wert zugeordnet oder das nicht verwandte Objekt gelöscht werden.</Message>
    <Stack>   bei System.Data.Entity.Core.Objects.ObjectContext.PrepareToSaveChanges(SaveOptions options)
   bei System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
   bei System.Data.Entity.Internal.InternalContext.SaveChanges()
   bei CardGame.DAL.Logic.DeckManager.UpdateDeckById(Int32 id, List`1 deckCards) in C:\Users\cervchri\Documents\GitHub\LAP-CardShop\CardGameLap\CardGame\CardGame.DAL\Logic\DeckManager.cs:Zeile 137.</Stack>
  </Exception>
</Xcpt>
<Info>
  <Time>20.06.2017 16:13:48</Time>
  <Info>id: 4</Info>
</Info>
<Info>
  <Time>20.06.2017 16:24:21</Time>
  <Info>id: 5</Info>
</Info>
<Info>
  <Time>20.06.2017 16:27:16</Time>
  <Info>id: 4</Info>
</Info>
<Info>
  <Time>20.06.2017 22:11:24</Time>
  <Info>Entered Pass = 123user!</Info>
</Info>
<Info>
  <Time>20.06.2017 22:11:25</Time>
  <Info>HashPass = 1D2FEF984B7AAF40382E4E544A63C11EF70BA6E3C55CC53C4EC6BD9BAA558360216ACE15C2EEEDB13C7A6E6C53B0EAEA4139CB1C1B3989C4F8E4DE2AA9750CAD</Info>
</Info>
<Info>
  <Time>20.06.2017 22:12:33</Time>
  <Info>id: 2</Info>
</Info>
<Info>
  <Time>20.06.2017 22:12:48</Time>
  <Info>id: 2</Info>
</Info>
<Info>
  <Time>20.06.2017 22:15:49</Time>
  <Info>Entered Pass = 123user!</Info>
</Info>
<Info>
  <Time>20.06.2017 22:15:49</Time>
  <Info>HashPass = 1D2FEF984B7AAF40382E4E544A63C11EF70BA6E3C55CC53C4EC6BD9BAA558360216ACE15C2EEEDB13C7A6E6C53B0EAEA4139CB1C1B3989C4F8E4DE2AA9750CAD</Info>
</Info>
<Info>
  <Time>20.06.2017 22:16:28</Time>
  <Info>id: 4</Info>
</Info>
<Info>
  <Time>20.06.2017 22:45:36</Time>
  <Info>Entered Pass = 123user!</Info>
</Info>
<Info>
  <Time>20.06.2017 22:45:36</Time>
  <Info>HashPass = 1D2FEF984B7AAF40382E4E544A63C11EF70BA6E3C55CC53C4EC6BD9BAA558360216ACE15C2EEEDB13C7A6E6C53B0EAEA4139CB1C1B3989C4F8E4DE2AA9750CAD</Info>
</Info>
<Info>
  <Time>20.06.2017 22:45:43</Time>
  <Info>id: 5</Info>
</Info>
<Info>
  <Time>20.06.2017 22:57:34</Time>
  <Info>Entered Pass = 123user!</Info>
</Info>
<Info>
  <Time>20.06.2017 22:57:34</Time>
  <Info>HashPass = 1D2FEF984B7AAF40382E4E544A63C11EF70BA6E3C55CC53C4EC6BD9BAA558360216ACE15C2EEEDB13C7A6E6C53B0EAEA4139CB1C1B3989C4F8E4DE2AA9750CAD</Info>
</Info>
<Xcpt>
  <Time>20.06.2017 23:12:00</Time>
  <Exception>
    <Source>EntityFramework</Source>
    <Message>Fehler beim zugrunde liegenden Anbieter auf Open.</Message>
    <Stack>   bei System.Data.Entity.Core.EntityClient.EntityConnection.Open()
   bei System.Data.Entity.Core.Objects.ObjectContext.EnsureConnection(Boolean shouldMonitorTransactions)
   bei System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   bei System.Data.Entity.Core.Objects.ObjectQuery`1.&lt;&gt;c__DisplayClass7.&lt;GetResults&gt;b__5()
   bei System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   bei System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   bei System.Data.Entity.Core.Objects.ObjectQuery`1.&lt;System.Collections.Generic.IEnumerable&lt;T&gt;.GetEnumerator&gt;b__0()
   bei System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   bei System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   bei System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.&lt;GetElementFunction&gt;b__1[TResult](IEnumerable`1 sequence)
   bei System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.ExecuteSingle[TResult](IEnumerable`1 query, Expression queryRoot)
   bei System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   bei System.Data.Entity.Internal.Linq.DbQueryProvider.Execute[TResult](Expression expression)
   bei System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
   bei CardGame.DAL.Logic.AuthManager.AuthUser(String email, String password) in C:\Users\Chris Artist\Documents\GitHub\LAP-CardShop\CardGameLap\CardGame\CardGame.DAL\Logic\AuthManager.cs:Zeile 54.</Stack>
    <InnerException>
      <Source>.Net SqlClient Data Provider</Source>
      <Message>Netzwerkbezogener oder instanzspezifischer Fehler beim Herstellen einer Verbindung mit SQL Server. Der Server wurde nicht gefunden, oder auf ihn kann nicht zugegriffen werden. Überprüfen Sie, ob der Instanzname richtig ist und ob SQL Server Remoteverbindungen zulässt. (provider: Named Pipes Provider, error: 40 - Verbindung mit SQL Server konnte nicht geöffnet werden)</Message>
      <Stack>   bei System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   bei System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   bei System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   bei System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   bei System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   bei System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   bei System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   bei System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   bei System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   bei System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   bei System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   bei System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   bei System.Data.SqlClient.SqlConnection.Open()
   bei System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.&lt;Open&gt;b__36(DbConnection t, DbConnectionInterceptionContext c)
   bei System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext](TTarget target, Action`2 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   bei System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.Open(DbConnection connection, DbInterceptionContext interceptionContext)
   bei System.Data.Entity.Core.EntityClient.EntityConnection.&lt;Open&gt;b__2()
   bei System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;&gt;c__DisplayClass1.&lt;Execute&gt;b__0()
   bei System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   bei System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute(Action operation)
   bei System.Data.Entity.Core.EntityClient.EntityConnection.Open()</Stack>
    </InnerException>
  </Exception>
</Xcpt>
<Xcpt>
  <Time>20.06.2017 23:12:00</Time>
  <Exception>
    <Source>EntityFramework</Source>
    <Message>Fehler beim zugrunde liegenden Anbieter auf Open.</Message>
    <Stack>   bei System.Data.Entity.Core.EntityClient.EntityConnection.Open()
   bei System.Data.Entity.Core.Objects.ObjectContext.EnsureConnection(Boolean shouldMonitorTransactions)
   bei System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   bei System.Data.Entity.Core.Objects.ObjectQuery`1.&lt;&gt;c__DisplayClass7.&lt;GetResults&gt;b__5()
   bei System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   bei System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   bei System.Data.Entity.Core.Objects.ObjectQuery`1.&lt;System.Collections.Generic.IEnumerable&lt;T&gt;.GetEnumerator&gt;b__0()
   bei System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   bei System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   bei System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.&lt;GetElementFunction&gt;b__1[TResult](IEnumerable`1 sequence)
   bei System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.ExecuteSingle[TResult](IEnumerable`1 query, Expression queryRoot)
   bei System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   bei System.Data.Entity.Internal.Linq.DbQueryProvider.Execute[TResult](Expression expression)
   bei System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
   bei CardGame.DAL.Logic.UserManager.GetRoleNamesByEmail(String email) in C:\Users\Chris Artist\Documents\GitHub\LAP-CardShop\CardGameLap\CardGame\CardGame.DAL\Logic\UserManager.cs:Zeile 118.</Stack>
    <InnerException>
      <Source>.Net SqlClient Data Provider</Source>
      <Message>Netzwerkbezogener oder instanzspezifischer Fehler beim Herstellen einer Verbindung mit SQL Server. Der Server wurde nicht gefunden, oder auf ihn kann nicht zugegriffen werden. Überprüfen Sie, ob der Instanzname richtig ist und ob SQL Server Remoteverbindungen zulässt. (provider: Named Pipes Provider, error: 40 - Verbindung mit SQL Server konnte nicht geöffnet werden)</Message>
      <Stack>   bei System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   bei System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   bei System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   bei System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   bei System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   bei System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   bei System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   bei System.Data.SqlClient.SqlConnection.Open()
   bei System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.&lt;Open&gt;b__36(DbConnection t, DbConnectionInterceptionContext c)
   bei System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext](TTarget target, Action`2 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   bei System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.Open(DbConnection connection, DbInterceptionContext interceptionContext)
   bei System.Data.Entity.Core.EntityClient.EntityConnection.&lt;Open&gt;b__2()
   bei System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;&gt;c__DisplayClass1.&lt;Execute&gt;b__0()
   bei System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   bei System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute(Action operation)
   bei System.Data.Entity.Core.EntityClient.EntityConnection.Open()</Stack>
    </InnerException>
  </Exception>
</Xcpt>
<Xcpt>
  <Time>20.06.2017 23:12:01</Time>
  <Exception>
    <Source>EntityFramework</Source>
    <Message>Fehler beim zugrunde liegenden Anbieter auf Open.</Message>
    <Stack>   bei System.Data.Entity.Core.EntityClient.EntityConnection.Open()
   bei System.Data.Entity.Core.Objects.ObjectContext.EnsureConnection(Boolean shouldMonitorTransactions)
   bei System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   bei System.Data.Entity.Core.Objects.ObjectQuery`1.&lt;&gt;c__DisplayClass7.&lt;GetResults&gt;b__5()
   bei System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   bei System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   bei System.Data.Entity.Core.Objects.ObjectQuery`1.&lt;System.Collections.Generic.IEnumerable&lt;T&gt;.GetEnumerator&gt;b__0()
   bei System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   bei System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   bei System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.&lt;GetElementFunction&gt;b__1[TResult](IEnumerable`1 sequence)
   bei System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.ExecuteSingle[TResult](IEnumerable`1 query, Expression queryRoot)
   bei System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   bei System.Data.Entity.Internal.Linq.DbQueryProvider.Execute[TResult](Expression expression)
   bei System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
   bei CardGame.DAL.Logic.UserManager.GetPersonByEmail(String email) in C:\Users\Chris Artist\Documents\GitHub\LAP-CardShop\CardGameLap\CardGame\CardGame.DAL\Logic\UserManager.cs:Zeile 84.</Stack>
    <InnerException>
      <Source>.Net SqlClient Data Provider</Source>
      <Message>Netzwerkbezogener oder instanzspezifischer Fehler beim Herstellen einer Verbindung mit SQL Server. Der Server wurde nicht gefunden, oder auf ihn kann nicht zugegriffen werden. Überprüfen Sie, ob der Instanzname richtig ist und ob SQL Server Remoteverbindungen zulässt. (provider: Named Pipes Provider, error: 40 - Verbindung mit SQL Server konnte nicht geöffnet werden)</Message>
      <Stack>   bei System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   bei System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   bei System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   bei System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   bei System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   bei System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   bei System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   bei System.Data.SqlClient.SqlConnection.Open()
   bei System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.&lt;Open&gt;b__36(DbConnection t, DbConnectionInterceptionContext c)
   bei System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext](TTarget target, Action`2 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   bei System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.Open(DbConnection connection, DbInterceptionContext interceptionContext)
   bei System.Data.Entity.Core.EntityClient.EntityConnection.&lt;Open&gt;b__2()
   bei System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;&gt;c__DisplayClass1.&lt;Execute&gt;b__0()
   bei System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   bei System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute(Action operation)
   bei System.Data.Entity.Core.EntityClient.EntityConnection.Open()</Stack>
    </InnerException>
  </Exception>
</Xcpt>
<Xcpt>
  <Time>20.06.2017 23:12:43</Time>
  <Exception>
    <Source>EntityFramework</Source>
    <Message>Fehler beim zugrunde liegenden Anbieter auf Open.</Message>
    <Stack>   bei System.Data.Entity.Core.EntityClient.EntityConnection.Open()
   bei System.Data.Entity.Core.Objects.ObjectContext.EnsureConnection(Boolean shouldMonitorTransactions)
   bei System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   bei System.Data.Entity.Core.Objects.ObjectQuery`1.&lt;&gt;c__DisplayClass7.&lt;GetResults&gt;b__5()
   bei System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   bei System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   bei System.Data.Entity.Core.Objects.ObjectQuery`1.&lt;System.Collections.Generic.IEnumerable&lt;T&gt;.GetEnumerator&gt;b__0()
   bei System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   bei System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   bei System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.&lt;GetElementFunction&gt;b__1[TResult](IEnumerable`1 sequence)
   bei System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.ExecuteSingle[TResult](IEnumerable`1 query, Expression queryRoot)
   bei System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   bei System.Data.Entity.Internal.Linq.DbQueryProvider.Execute[TResult](Expression expression)
   bei System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
   bei CardGame.DAL.Logic.AuthManager.AuthUser(String email, String password) in C:\Users\Chris Artist\Documents\GitHub\LAP-CardShop\CardGameLap\CardGame\CardGame.DAL\Logic\AuthManager.cs:Zeile 54.</Stack>
    <InnerException>
      <Source>.Net SqlClient Data Provider</Source>
      <Message>Netzwerkbezogener oder instanzspezifischer Fehler beim Herstellen einer Verbindung mit SQL Server. Der Server wurde nicht gefunden, oder auf ihn kann nicht zugegriffen werden. Überprüfen Sie, ob der Instanzname richtig ist und ob SQL Server Remoteverbindungen zulässt. (provider: Named Pipes Provider, error: 40 - Verbindung mit SQL Server konnte nicht geöffnet werden)</Message>
      <Stack>   bei System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   bei System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   bei System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   bei System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   bei System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   bei System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   bei System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   bei System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   bei System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   bei System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   bei System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   bei System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   bei System.Data.SqlClient.SqlConnection.Open()
   bei System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.&lt;Open&gt;b__36(DbConnection t, DbConnectionInterceptionContext c)
   bei System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext](TTarget target, Action`2 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   bei System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.Open(DbConnection connection, DbInterceptionContext interceptionContext)
   bei System.Data.Entity.Core.EntityClient.EntityConnection.&lt;Open&gt;b__2()
   bei System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;&gt;c__DisplayClass1.&lt;Execute&gt;b__0()
   bei System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   bei System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute(Action operation)
   bei System.Data.Entity.Core.EntityClient.EntityConnection.Open()</Stack>
    </InnerException>
  </Exception>
</Xcpt>
<Xcpt>
  <Time>20.06.2017 23:12:43</Time>
  <Exception>
    <Source>EntityFramework</Source>
    <Message>Fehler beim zugrunde liegenden Anbieter auf Open.</Message>
    <Stack>   bei System.Data.Entity.Core.EntityClient.EntityConnection.Open()
   bei System.Data.Entity.Core.Objects.ObjectContext.EnsureConnection(Boolean shouldMonitorTransactions)
   bei System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   bei System.Data.Entity.Core.Objects.ObjectQuery`1.&lt;&gt;c__DisplayClass7.&lt;GetResults&gt;b__5()
   bei System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   bei System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   bei System.Data.Entity.Core.Objects.ObjectQuery`1.&lt;System.Collections.Generic.IEnumerable&lt;T&gt;.GetEnumerator&gt;b__0()
   bei System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   bei System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   bei System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.&lt;GetElementFunction&gt;b__1[TResult](IEnumerable`1 sequence)
   bei System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.ExecuteSingle[TResult](IEnumerable`1 query, Expression queryRoot)
   bei System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   bei System.Data.Entity.Internal.Linq.DbQueryProvider.Execute[TResult](Expression expression)
   bei System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
   bei CardGame.DAL.Logic.UserManager.GetRoleNamesByEmail(String email) in C:\Users\Chris Artist\Documents\GitHub\LAP-CardShop\CardGameLap\CardGame\CardGame.DAL\Logic\UserManager.cs:Zeile 118.</Stack>
    <InnerException>
      <Source>.Net SqlClient Data Provider</Source>
      <Message>Netzwerkbezogener oder instanzspezifischer Fehler beim Herstellen einer Verbindung mit SQL Server. Der Server wurde nicht gefunden, oder auf ihn kann nicht zugegriffen werden. Überprüfen Sie, ob der Instanzname richtig ist und ob SQL Server Remoteverbindungen zulässt. (provider: Named Pipes Provider, error: 40 - Verbindung mit SQL Server konnte nicht geöffnet werden)</Message>
      <Stack>   bei System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   bei System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   bei System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   bei System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   bei System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   bei System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   bei System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   bei System.Data.SqlClient.SqlConnection.Open()
   bei System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.&lt;Open&gt;b__36(DbConnection t, DbConnectionInterceptionContext c)
   bei System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext](TTarget target, Action`2 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   bei System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.Open(DbConnection connection, DbInterceptionContext interceptionContext)
   bei System.Data.Entity.Core.EntityClient.EntityConnection.&lt;Open&gt;b__2()
   bei System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;&gt;c__DisplayClass1.&lt;Execute&gt;b__0()
   bei System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   bei System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute(Action operation)
   bei System.Data.Entity.Core.EntityClient.EntityConnection.Open()</Stack>
    </InnerException>
  </Exception>
</Xcpt>
<Xcpt>
  <Time>20.06.2017 23:12:43</Time>
  <Exception>
    <Source>EntityFramework</Source>
    <Message>Fehler beim zugrunde liegenden Anbieter auf Open.</Message>
    <Stack>   bei System.Data.Entity.Core.EntityClient.EntityConnection.Open()
   bei System.Data.Entity.Core.Objects.ObjectContext.EnsureConnection(Boolean shouldMonitorTransactions)
   bei System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   bei System.Data.Entity.Core.Objects.ObjectQuery`1.&lt;&gt;c__DisplayClass7.&lt;GetResults&gt;b__5()
   bei System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   bei System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   bei System.Data.Entity.Core.Objects.ObjectQuery`1.&lt;System.Collections.Generic.IEnumerable&lt;T&gt;.GetEnumerator&gt;b__0()
   bei System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   bei System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   bei System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.&lt;GetElementFunction&gt;b__1[TResult](IEnumerable`1 sequence)
   bei System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.ExecuteSingle[TResult](IEnumerable`1 query, Expression queryRoot)
   bei System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   bei System.Data.Entity.Internal.Linq.DbQueryProvider.Execute[TResult](Expression expression)
   bei System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
   bei CardGame.DAL.Logic.UserManager.GetPersonByEmail(String email) in C:\Users\Chris Artist\Documents\GitHub\LAP-CardShop\CardGameLap\CardGame\CardGame.DAL\Logic\UserManager.cs:Zeile 84.</Stack>
    <InnerException>
      <Source>.Net SqlClient Data Provider</Source>
      <Message>Netzwerkbezogener oder instanzspezifischer Fehler beim Herstellen einer Verbindung mit SQL Server. Der Server wurde nicht gefunden, oder auf ihn kann nicht zugegriffen werden. Überprüfen Sie, ob der Instanzname richtig ist und ob SQL Server Remoteverbindungen zulässt. (provider: Named Pipes Provider, error: 40 - Verbindung mit SQL Server konnte nicht geöffnet werden)</Message>
      <Stack>   bei System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   bei System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   bei System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   bei System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   bei System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   bei System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   bei System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   bei System.Data.SqlClient.SqlConnection.Open()
   bei System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.&lt;Open&gt;b__36(DbConnection t, DbConnectionInterceptionContext c)
   bei System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext](TTarget target, Action`2 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   bei System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.Open(DbConnection connection, DbInterceptionContext interceptionContext)
   bei System.Data.Entity.Core.EntityClient.EntityConnection.&lt;Open&gt;b__2()
   bei System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;&gt;c__DisplayClass1.&lt;Execute&gt;b__0()
   bei System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   bei System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute(Action operation)
   bei System.Data.Entity.Core.EntityClient.EntityConnection.Open()</Stack>
    </InnerException>
  </Exception>
</Xcpt>
<Info>
  <Time>20.06.2017 23:14:51</Time>
  <Info>Entered Pass = 123user!</Info>
</Info>
<Info>
  <Time>20.06.2017 23:14:52</Time>
  <Info>HashPass = 1D2FEF984B7AAF40382E4E544A63C11EF70BA6E3C55CC53C4EC6BD9BAA558360216ACE15C2EEEDB13C7A6E6C53B0EAEA4139CB1C1B3989C4F8E4DE2AA9750CAD</Info>
</Info>
